### ISSUE TITLE
Problems with Docker container

### ISSUE THREAD

**Issue by BenPashley** [RationAI/xopat#52] opened 2024-06-12 16:00 UTC
Hi,

I am very interested in evaluating your viewer.  When following your docker instructions I get the following error: 

**Not Found
The requested URL was not found on this server.
Apache/2.4.52 (Ubuntu) Server at localhost Port 8080**

Are there any updated configuration instructions for using docker example? 

Any further help or instructions would be much appreciated.

Ben

**Comment by Aiosa** [comment] 2024-06-24 11:28
Hi, thanks for the interest! Sorry, I did not notice the issue eariler. Since then I've merged the development branch. The docker PHP image can be simply run via `docker compose -f docker/php/docker-compose.yml up` , and there is a node server available too. If you arrive at any issues, please, let me know.

**Comment by Aiosa** [comment] 2024-08-23 05:40
Considering this as a closed issue, since I could not reproduce the issue with the latest version. Please reopen if this will be still relevant.

**Closed by Aiosa** 2024-08-23 05:40 UTC
